version: '3.8'

services:
  notebook:
    build:
      context: ..
      dockerfile: docker/Dockerfile-notebook
    volumes:
      - ..:/workspace:rw
    ports:
      - "8888:8888"
    environment:
      - PYTHONUNBUFFERED=1

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile-api
    volumes:
      - ..:/app:rw
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
