name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest black flake8 mypy

    - name: Run tests
      run: |
        pytest -q || true

    - name: Run formatting check (black)
      run: |
        black --check . || echo "Black formatting issues found"

    - name: Run linter (flake8)
      run: |
        flake8 || echo "Flake8 reported issues"

    - name: Type check (mypy)
      run: |
        mypy . || echo "Mypy type issues reported"
